### ISSUE TITLE
I have some questions that need your answer.

### ISSUE THREAD

**Issue by SandLYJ** [pc-cp/MSVQ#1]
Hello, I am a student from SCAU，my major is deep clustering, I find your idea is very fantastic, but I have some question about the code  in msvq.py (the lablel is need to do what? is it a ture label?),
I am looking forward to your early reply.thanks.

**Comment by pc-cp** [comment]
Thank you very much for your attention. Are you referring to the 'labels' at https://github.com/pc-cp/MSVQ/blob/78c46d49930b26efba5afeb2d0e637d1eae2e2a2/main.py#L94? You are correct, they are the true labels. However, these 'labels' are updated to https://github.com/pc-cp/MSVQ/blob/78c46d49930b26efba5afeb2d0e637d1eae2e2a2/util/MemoryBankModule.py#L128, which means the labels are not used by the model itself. This is because of self-supervised learning. As for why MemoryBankModule.py needs labels? It is for analyzing the neighbor purity in algorithms like NNCLR, MSF, etc. Hope this helps you. For more you can also refer to https://github.com/pc-cp/Mini-SSL.

**Comment by SandLYJ** [comment]
Thank you very much!
Your answer  is  vital for me!
 You are my star!

ChenPeng(彭晨) ***@***.***> 于2023年11月30日周四 10:58写道：
